#!/bin/bash

# This bash script runs the cGoTests in the current directory

reset

echo "------------------------------------------------------------"
echo "generating cGoTests"
echo "------------------------------------------------------------"
go generate -tags cGoTests
echo "------------------------------------------------------------"
echo ""

echo "------------------------------------------------------------"
echo "running cGoTests"
echo "------------------------------------------------------------"
go test -tags cGoTests
echo "------------------------------------------------------------"
echo ""
